extends: default

rules:
  line-length: disable
  comments: disable
  comments-indentation: disable
  document-start: disable

ignore: |
  custom_components/
  www/community/
  zigbee2mqtt/
  themes/
  blueprints/
  pyscript/
  automations.yaml
  scripts.yaml
  scenes.yaml
  ui-lovelace.yaml
