- id: '1638712108991'
  alias: Sync shopping list
  description: ''
  trigger:
  - platform: webhook
    webhook_id: sync_shopping_list
    id: sync_shopping_list
  condition: []
  action:
  - service: pyscript.sync_shopping_list
  mode: single
- id: '1644331745972'
  alias: '[Notify][Energy] High Consumption'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.frient_energy_monitor_power
    for:
      hours: 0
      minutes: 0
      seconds: 20
    above: 4600
  condition:
  - condition: state
    entity_id: switch.water_heater
    state: 'off'
  action:
  - service: notify.aronne
    data:
      title: ⚡️ *Sto consumando troppo!*
      message: I consumi hanno superato i 4.6kW per 20 secondi e il boiler è già spento,
        se non spegni qualcosa salterà la corrente!
  mode: single
- id: '1644433874893'
  alias: '[Notify][Proxmox] High Memory Usage'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.proxmox_memory_usage
    above: '13'
  condition: []
  action:
  - service: notify.aronne
    data:
      title: ⚠️ *Proxmox high memory usage*
      message: Superati i 13GB di RAM occupata
  mode: single
- id: '1650365699588'
  alias: '[Notify][Garbage Collection] Tomorrow garbage collection'
  description: Send Telegram notification at 6:00PM for garbage collection occurring
    the next day
  trigger:
  - platform: calendar
    event: start
    offset: '-6:00:0'
    entity_id: calendar.garbage_collection
  condition: []
  action:
  - service: notify.aronne
    data:
      title: "\U0001F6AE *Raccolta rifiuti*"
      message: Domani passano a ritirare la spazzatura! [Dettagli](https://home.aronnebrivio.dev/lovelace/kitchen)
  mode: single
- id: '1650473639566'
  alias: Button 1 manage Piantana Sala
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Button 1/action
    payload: single
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.piantana_sala
  mode: single
- id: '1650473927334'
  alias: Button 2 manage Luce Letto
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Button 2/action
    payload: single
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.bed
  mode: single
- id: '1651408183906'
  alias: '[Energy] High consumption -> turn water heater off'
  description: If energy consumption go below a threshold, turn the boiler off and
    send a notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.frient_energy_monitor_power
    above: 4600
  condition:
  - condition: state
    entity_id: switch.water_heater
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.water_heater
  - service: notify.aronne
    data:
      title: "\U0001F6BF *Ho spento il boiler per limitare i consumi*"
      message: I consumi istantanei hanno superato i 4.6kW, cosí ho spento il boiler
        per cercare di limitarli. [Dettagli](https://iqf2y6yscdio5ilo35kpfrxbyqfpreyl.ui.nabu.casa/lovelace/kitchen)
  mode: single
- id: '1651526561767'
  alias: '[Boiler] Turn on at 6:00 AM on working days'
  description: Turn on boiler at 6:00 AM on working days if it was off
  trigger:
  - platform: time
    at: 06:00:00
  condition:
  - condition: state
    entity_id: switch.water_heater
    state: 'off'
  - condition: time
    before: '10:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 01:00:00
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.water_heater
  mode: single
- id: '1652082753955'
  alias: '[Notify] HA Update'
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: '3'
      update_entities:
      - update.home_assistant_supervisor_update
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      mobile_app_device: 905677963a9b6082d24810268358ebec
- id: '1658824207858'
  alias: Re-Load Speed Test
  description: Perform a Manual Speed Test when sensor goes offline
  trigger:
  - platform: state
    entity_id:
    - sensor.speedtest_download
    to: unavailable
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.speedtest_download
      state: unavailable
    - condition: state
      entity_id: sensor.speedtest_download
      state: unknown
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.speedtest_download
  mode: single
- id: '1677317734499'
  alias: '[NFC][PC] On'
  description: ''
  trigger:
  - platform: tag
    tag_id: 47303df8-67a6-4f83-8c66-c4198583bb2e
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.gaming_station
  mode: single
- id: '1677318448444'
  alias: '[NFC][Door] Exit'
  description: Turn off all lights if any is on
  trigger:
  - platform: tag
    tag_id: d9cce178-68e9-4c85-a716-3d541422e054
  condition:
  - condition: template
    value_template: '{{ states.light|selectattr(''state'',''equalto'',''on'')|list|length
      > 0 }}'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: all
  - service: climate.turn_off
    data: {}
    target:
      entity_id: all
  mode: single
- id: '1677323384344'
  alias: '[NFC][Door] Enter'
  description: 'Turn on entrance lights if none are on '
  trigger:
  - platform: tag
    tag_id: d9cce178-68e9-4c85-a716-3d541422e054
  condition:
  - condition: template
    value_template: '{{ states.light|selectattr(''state'',''equalto'',''on'')|list|length
      == 0 }}'
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.piantana_sala
  mode: single
- id: '1677479754729'
  alias: '[NFC][Bed] Lights off'
  description: Turn off bed lights
  trigger:
  - platform: tag
    tag_id: 515ace01-e5e2-41fc-bc5f-1b138fb30c35
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bed
  mode: single
- id: '1686580227765'
  alias: '[Climate] Turn Bedroom AC on during night if temp above 26.2'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.termometro_camera_temperature
  condition:
  - condition: time
    after: '22:30:00'
    before: 07:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  - condition: numeric_state
    entity_id: sensor.termometro_camera_temperature
    attribute: temperature
    above: 26.2
  - condition: state
    entity_id: climate.condizionatore_camera
    state: 'off'
  action:
  - service: climate.turn_on
    data: {}
    target:
      entity_id: climate.condizionatore_camera
  mode: single
- id: '1687416869637'
  alias: '[Climate] Turn Bedroom AC off during night if temp under 25.2'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.termometro_camera_temperature
  condition:
  - condition: time
    after: '22:30:00'
    before: 07:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  - condition: numeric_state
    entity_id: sensor.termometro_camera_temperature
    attribute: temperature
    below: 25.2
  - condition: state
    entity_id: climate.condizionatore_camera
    state: cool
  action:
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.condizionatore_camera
  mode: single
