- id: '1644331745972'
  alias: '[Notify][Energy] High Consumption'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.frient_energy_monitor_power
    for:
      hours: 0
      minutes: 0
      seconds: 20
    above: 4600
  condition:
  - condition: state
    entity_id: switch.water_heater
    state: 'off'
  action:
  - service: notify.aronne
    data:
      title: ⚡️ *Sto consumando troppo!*
      message: I consumi hanno superato i 4.6kW per 20 secondi e il boiler è già spento,
        se non spegni qualcosa salterà la corrente!
  mode: single
- id: '1644433874893'
  alias: '[Notify][Proxmox] High Memory Usage'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.proxmox_memory_usage
    above: '13'
  condition: []
  action:
  - service: notify.aronne
    data:
      title: ⚠️ *Proxmox high memory usage*
      message: Superati i 13GB di RAM occupata
  mode: single
- id: '1650365699588'
  alias: '[Notify][Garbage Collection] Tomorrow garbage collection'
  description: Send Telegram notification at 6:00PM for garbage collection occurring
    the next day
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.garbage_collection_tomorrow
    from: 'off'
    to: 'on'
    for:
      hours: 18
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.aronne
    data:
      title: "\U0001F6AE *Raccolta rifiuti*"
      message: Domani passano a ritirare la spazzatura! [Dettagli](https://home.aronnebrivio.dev/lovelace/kitchen)
  mode: single
- id: '1650473639566'
  alias: Buttons 2 manages Bed
  description: ''
  triggers:
  - domain: mqtt
    device_id: 0251771331478dd7458fcdb1dbadb35f
    type: action
    subtype: single
    trigger: device
  conditions: []
  actions:
  - data: {}
    action: light.toggle
    target:
      entity_id: light.bed
  mode: single
- id: '1651408183906'
  alias: '[Energy] High consumption -> turn water heater off'
  description: If energy consumption go below a threshold, turn the boiler off and
    send a notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.frient_energy_monitor_power
    above: 4600
  condition:
  - condition: state
    entity_id: switch.water_heater
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.water_heater
  - service: notify.aronne
    data:
      title: "\U0001F6BF *Ho spento il boiler per limitare i consumi*"
      message: I consumi istantanei hanno superato i 4.6kW, cosí ho spento il boiler
        per cercare di limitarli. [Dettagli](https://iqf2y6yscdio5ilo35kpfrxbyqfpreyl.ui.nabu.casa/lovelace/kitchen)
  mode: single
- id: '1651526561767'
  alias: '[Boiler] Turn on at 5:00 AM on working days'
  description: Turn on boiler at 5:00 AM on working days if it was off
  trigger:
  - platform: time
    at: 05:00:00
  condition:
  - condition: state
    entity_id: switch.water_heater
    state: 'off'
  - condition: time
    before: '10:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    after: 01:00:00
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.water_heater
  mode: single
- id: '1652082753955'
  alias: '[Notify] HA Update'
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: '3'
      update_entities:
      - update.home_assistant_supervisor_update
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      mobile_app_device: cf132f484fa5f5c742094b43402043b3
      mobile_app_device_2: 0aa5cbd661ef17ae46ea03b9fabf7ea9
- id: '1658824207858'
  alias: Re-Load Speed Test
  description: Perform a Manual Speed Test when sensor goes offline
  trigger:
  - platform: state
    entity_id:
    - sensor.speedtest_download
    to: unavailable
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.speedtest_download
      state: unavailable
    - condition: state
      entity_id: sensor.speedtest_download
      state: unknown
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.speedtest_download
  mode: single
- id: '1677317734499'
  alias: '[NFC][PC] On'
  description: ''
  trigger:
  - platform: tag
    tag_id: 47303df8-67a6-4f83-8c66-c4198583bb2e
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.gaming_station
  mode: single
- id: '1677318448444'
  alias: '[NFC][Door] Exit'
  description: Turn off all lights if any is on
  trigger:
  - platform: tag
    tag_id: d9cce178-68e9-4c85-a716-3d541422e054
  condition:
  - condition: template
    value_template: '{{ states.light|selectattr(''state'',''equalto'',''on'')|list|length
      > 0 }}'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: all
  - service: climate.turn_off
    data: {}
    target:
      entity_id: all
  mode: single
- id: '1677323384344'
  alias: '[NFC][Door] Enter'
  description: 'Turn on entrance lights if none are on '
  trigger:
  - platform: tag
    tag_id: d9cce178-68e9-4c85-a716-3d541422e054
  condition:
  - condition: template
    value_template: '{{ states.light|selectattr(''state'',''equalto'',''on'')|list|length
      == 0 }}'
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.piantana_sala
  mode: single
- id: '1677479754729'
  alias: '[NFC][Bed] Lights toggle'
  description: Toggle bed lights
  triggers:
  - tag_id: 515ace01-e5e2-41fc-bc5f-1b138fb30c35
    trigger: tag
  conditions: []
  actions:
  - action: light.toggle
    target:
      entity_id:
      - light.bed
    data: {}
  mode: single
- id: '1686580227765'
  alias: '[Climate] Turn Bedroom AC on during night if temp above 26.2'
  description: ''
  triggers:
  - entity_id:
    - sensor.termometro_camera_temperature
    trigger: state
  - trigger: time
    at: '22:30:00'
  conditions:
  - condition: time
    after: '22:30:00'
    before: 07:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  - type: is_not_open
    condition: device
    device_id: 5637589d3b0d75f6fcaca3854ec8a669
    entity_id: 9b865db4cc02087c5c2c3316f71afb84
    domain: binary_sensor
  - condition: numeric_state
    entity_id: sensor.termometro_camera_temperature
    above: 26.2
  - condition: state
    entity_id: climate.condizionatore_camera
    state: 'off'
  actions:
  - data: {}
    target:
      entity_id: climate.condizionatore_camera
    action: climate.turn_on
  mode: single
- id: '1687416869637'
  alias: '[Climate] Turn Bedroom AC off during night if temp under 25.2'
  description: ''
  triggers:
  - entity_id:
    - sensor.termometro_camera_temperature
    trigger: state
  conditions:
  - condition: time
    after: '22:30:00'
    before: 07:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  - condition: numeric_state
    entity_id: sensor.termometro_camera_temperature
    below: 25.2
  - condition: state
    entity_id: climate.condizionatore_camera
    state: cool
  actions:
  - data: {}
    target:
      entity_id: climate.condizionatore_camera
    action: climate.turn_off
  mode: single
- id: '1728838134324'
  alias: '[NFC][Vetrina Ingresso] Light toggle'
  description: Toggle vetrina ingresso light
  triggers:
  - trigger: tag
    tag_id: 0d891f34-721d-43b2-b33d-87c570913883
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.vetrina_ingresso
  mode: single
- id: '1730656163756'
  alias: '[Notify][Air Quality] Poor indoor AQI'
  description: ''
  triggers:
  - entity_id:
    - sensor.indoor_aqi
    for:
      hours: 0
      minutes: 30
      seconds: 0
    above: 100
    trigger: numeric_state
  conditions:
  - condition: numeric_state
    entity_id: sensor.u_s_air_quality_index
    attribute: state
    below: 100
  actions:
  - data:
      title: "\U0001F4A8 *Apri le finestre!*"
      message: La qualità dell'aria di casa è scarsa, fai cambiare aria che non si
        respira!
    action: notify.aronne
  mode: single
- id: '1730656544836'
  alias: '[Notify][Air Quality] High Outdoor AQI'
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.u_s_air_quality_index
    for:
      hours: 0
      minutes: 30
      seconds: 0
    attribute: state
    above: 150
  conditions: []
  actions:
  - data:
      title: "\U0001FA9F *Chiudi tutto!*"
      message: La qualità dell'aria fuori fa schifo, tappati in casa!
    action: notify.aronne
  mode: single
- id: '1746726664304'
  alias: Remote Dimmer 1 on press Piantana Sala
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9aa938026d3f8b95235300704c7fa455
    type: action
    subtype: on_press_release
    trigger: device
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: light.piantana_sala
    action: light.toggle
  mode: single
- id: '1746727135690'
  alias: Remote Dimmer 1 up press Piantana Sala
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9aa938026d3f8b95235300704c7fa455
    type: action
    subtype: up_press_release
    trigger: device
  conditions: []
  actions:
  - device_id: 01c9c8562a6a20b1ab0830e09a3a05c7
    domain: light
    entity_id: 0165dd4c86cdff9e3cf316879aca6e8d
    type: brightness_increase
  - device_id: e7e59260a8951fd7fe729e4408e80afa
    domain: light
    entity_id: 385f78d48816d02dbdd64c67d5479977
    type: brightness_increase
  mode: single
- id: '1746727202712'
  alias: Remote Dimmer 1 down press Piantana Sala
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9aa938026d3f8b95235300704c7fa455
    type: action
    subtype: down_press_release
    trigger: device
  conditions: []
  actions:
  - device_id: 01c9c8562a6a20b1ab0830e09a3a05c7
    domain: light
    entity_id: 0165dd4c86cdff9e3cf316879aca6e8d
    type: brightness_decrease
  - device_id: e7e59260a8951fd7fe729e4408e80afa
    domain: light
    entity_id: 385f78d48816d02dbdd64c67d5479977
    type: brightness_decrease
  mode: single
- id: '1746727322708'
  alias: Remote Dimmer 1 off press Piantana Sala - Off
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9aa938026d3f8b95235300704c7fa455
    type: action
    subtype: off_press_release
    trigger: device
  conditions:
  - condition: device
    type: is_off
    device_id: 01c9c8562a6a20b1ab0830e09a3a05c7
    entity_id: 0165dd4c86cdff9e3cf316879aca6e8d
    domain: light
  - condition: device
    type: is_off
    device_id: e7e59260a8951fd7fe729e4408e80afa
    entity_id: 385f78d48816d02dbdd64c67d5479977
    domain: light
  actions:
  - action: adaptive_lighting.set_manual_control
    metadata: {}
    data:
      manual_control: true
      lights:
      - light.piantana_sala
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 30
      transition: 0.5
    target:
      entity_id: light.piantana_sala
  mode: single
- id: '1746727673822'
  alias: Remote Dimmer 1 off press Piantana Sala - On
  description: ''
  triggers:
  - domain: mqtt
    device_id: 9aa938026d3f8b95235300704c7fa455
    type: action
    subtype: off_press_release
    trigger: device
  conditions:
  - condition: device
    type: is_on
    device_id: 01c9c8562a6a20b1ab0830e09a3a05c7
    entity_id: 0165dd4c86cdff9e3cf316879aca6e8d
    domain: light
  - condition: device
    type: is_on
    device_id: e7e59260a8951fd7fe729e4408e80afa
    entity_id: 385f78d48816d02dbdd64c67d5479977
    domain: light
  actions:
  - action: adaptive_lighting.set_manual_control
    metadata: {}
    data:
      manual_control: true
      lights:
      - light.piantana_sala
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
      transition: 0.5
      color_temp_kelvin: 4980
    target:
      entity_id: light.piantana_sala
  mode: single
- id: '1751812485114'
  alias: Button 1 toggles Work Station
  description: ''
  triggers:
  - domain: mqtt
    device_id: e16495c4292c04093abe72449fb4e420
    type: action
    subtype: single
    trigger: device
  conditions: []
  actions:
  - action: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.casse_pc
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.luce_scrivania
  mode: single
