# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes

rest_command:
  switchbot_device_command:
    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot.api_key
    payload: '{"command": "{{ command }}"}'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch: !include entities/switches.yaml
media_player: !include entities/media_players.yaml
device_tracker: !include entities/device_trackers.yaml
sensor: !include entities/sensors.yaml
binary_sensor: !include entities/binary_sensors.yaml
light: !include entities/lights.yaml
utility_meter: !include entities/utility_meters.yaml
climate: !include entities/climates.yaml

pyscript: !include pyscript/config.yaml

python_script:

api:

alexa:
  smart_home:
    filter:
      exclude_entities:
        - light.piantana_sala_luce_grande
        - light.piantana_sala_luce_piccola
        - media_player.fire_tv
        - media_player.firestick
        - media_player.ovunque
        - switch.abat_jour_letto_sinistra_do_not_disturb
        - switch.bedroom_air_conditioner
        - switch.dummy_switch
      exclude_entity_globs:
        - light.patriot_viper_steel_rgb*
        - light.nzxt_smart_device*
        - light.asus_tuf_gaming_b460_plus*
        - media_player.echo*
        - media_player.spotify*
        - switch.adguard*
        - switch.aronne*
        - switch.bandabrivio*
        - switch.echo*
        - switch.circadian_lighting*
        - switch.fire_tv*
        - switch.ovunque*
        - switch.smart_plug*
        - switch.transmission*
      exclude_domains:
        - alarm_control_panel
        - alert
        - automation
        - binary_sensor
        - calendar
        - device_tracker
        - group
        - input_boolean
        - input_button
        - input_datetime
        - input_number
        - input_select
        - lock
        - number
        - person
        - remote
        - script
        - select
        - sensor
        - siren
        - timer
        - update
        - weather
        - zone

google_assistant:
  project_id: !secret google_assistant.project_id
  service_account: {
    "type": "service_account",
    "project_id": !secret google_assistant.project_id,
    "private_key_id": !secret google_assistant.private_key_id,
    "private_key": !secret google_assistant.private_key,
    "client_email": !secret google_assistant.client_email,
    "client_id": !secret google_assistant.client_id,
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": !secret google_assistant.client_x509_cert_url,
    "universe_domain": "googleapis.com"
  }
  report_state: true
  exposed_domains:
    - switch
    - light
    - media_player
    - climate

homekit:
  filter:
    exclude_entities:
      - light.piantana_sala_luce_grande
      - light.piantana_sala_luce_piccola
      - media_player.fire_tv
      - media_player.firestick
      - media_player.ovunque
      - switch.abat_jour_letto_sinistra_do_not_disturb
      - switch.bedroom_air_conditioner
      - switch.dummy_switch
    exclude_entity_globs:
      - light.patriot_viper_steel_rgb*
      - light.nzxt_smart_device*
      - light.asus_tuf_gaming_b460_plus*
      - media_player.echo*
      - media_player.spotify*
      - switch.adguard*
      - switch.aronne*
      - switch.bandabrivio*
      - switch.echo*
      - switch.circadian_lighting*
      - switch.fire_tv*
      - switch.ovunque*
      - switch.smart_plug*
      - switch.transmission*
    exclude_domains:
      - alarm_control_panel
      - alert
      - automation
      - binary_sensor
      - calendar
      - device_tracker
      - group
      - input_boolean
      - input_button
      - input_datetime
      - input_number
      - input_select
      - lock
      - number
      - person
      - remote
      - script
      - select
      - sensor
      - siren
      - timer
      - update
      - weather
      - zone

adaptive_lighting:
  lights:
    - light.bed
    - light.luce_scrivania
    - light.livingroom
  min_brightness: 10
  max_brightness: 100
  min_color_temp: 2000
  max_color_temp: 5500
  take_over_control: true
  detect_non_ha_changes: true

spotcast:
  sp_dc: !secret spotify.dc
  sp_key: !secret spotify.key

influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb.ip
  port: !secret influxdb.port
  token: !secret influxdb.token
  organization: !secret influxdb.organization_id
  bucket: !secret influxdb.bucket
  exclude:
    entity_globs: "*"

telegram_bot:
  - platform: polling
    api_key: !secret telegram.bot.token
    allowed_chat_ids:
      - !secret telegram.aronne.chat_id

notify:
  - platform: telegram
    name: !secret telegram.aronne.slug
    chat_id: !secret telegram.aronne.chat_id

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret network.local.subnet
    - !secret nginx_proxy_manager.ip

ifttt:
  key: !secret ifttt.api_key

duckdns:
  domain: !secret duckdns.subdomain
  access_token: !secret duckdns.access_token

smartir:
