# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes

rest_command:
  switchbot_device_command:
    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot.api_key
    payload: '{"command": "{{ command }}"}'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch: !include entities/switches.yaml
media_player: !include entities/media_players.yaml
device_tracker: !include entities/device_trackers.yaml
sensor: !include entities/sensors.yaml
binary_sensor: !include entities/binary_sensors.yaml
light: !include entities/lights.yaml
utility_meter: !include entities/utility_meters.yaml

pyscript: !include pyscript/config.yaml

python_script:

api:

circadian_lighting:
  max_colortemp: 5000
  min_colortemp: 2857
  interval: 600
  transition: 60

spotcast:
  sp_dc: !secret spotify.dc
  sp_key: !secret spotify.key

influxdb:
  host: !secret influxdb.ip
  database: !secret influxdb.database
  exclude:
    entity_globs: "*"

telegram_bot:
  - platform: polling
    api_key: !secret telegram.bot.token
    allowed_chat_ids:
      - !secret telegram.aronne.chat_id

notify:
  - platform: telegram
    name: !secret telegram.aronne.slug
    chat_id: !secret telegram.aronne.chat_id

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret network.local.subnet
    - !secret nginx_proxy_manager.ip

ifttt:
  key: !secret ifttt.api_key

duckdns:
  domain: duckdns.subdomain
  access_token: duckdns.access_token
