# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include entities/switches.yaml
media_player: !include entities/media_players.yaml
device_tracker: !include entities/device_trackers.yaml
sensor: !include entities/sensors.yaml
binary_sensor: !include entities/binary_sensors.yaml
light: !include entities/lights.yaml
utility_meter: !include entities/utility_meters.yaml
climate: !include entities/climates.yaml

api:

smartir:

alexa: !include voice_assistants/alexa.yaml
google_assistant: !include voice_assistants/google_assistant.yaml
homekit: !include voice_assistants/homekit.yaml

rest_command:
  switchbot_device_command:
    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot.api_key
    payload: '{"command": "{{ command }}"}'

adaptive_lighting:
  lights:
    - light.bed
    - light.luce_scrivania
    - light.livingroom
  min_brightness: 10
  max_brightness: 100
  min_color_temp: 2000
  max_color_temp: 5500
  take_over_control: true
  detect_non_ha_changes: true

spotcast:
  sp_dc: !secret spotify.dc
  sp_key: !secret spotify.key

influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb.ip
  port: !secret influxdb.port
  token: !secret influxdb.token
  organization: !secret influxdb.organization_id
  bucket: !secret influxdb.bucket
  exclude:
    entity_globs: "*"

telegram_bot:
  - platform: polling
    api_key: !secret telegram.bot.token
    allowed_chat_ids:
      - !secret telegram.aronne.chat_id

notify:
  - platform: telegram
    name: !secret telegram.aronne.slug
    chat_id: !secret telegram.aronne.chat_id

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret network.local.subnet
    - 172.30.33.0/24

ifttt:
  key: !secret ifttt.api_key

readme:
  convert_lovelace: true

waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: calendars/garbage_collection.ics
      calendar_title: Garbage Collection
