# Describes the format for available OpenRGB services

pull_devices:
  name: Pull devices
  description: Pulls device list from OpenRGB server.

force_update:
  name: Force update
  description: Forces all OpenRGB devices to pull data.

load_profile:
  name: Load profile
  description: Load a profile on OpenRGB server.
  fields:
    profile:
      name: Profile
      description: The name of the profile to load.
      required: true
      selector:
        text:
