esphome:
  name: esp8266-02
  friendly_name: esp8266-02

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp8266-02.api.encryption_key

ota:
  - platform: esphome
    password: !secret esp8266-02.ota.password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-02 Fallback Hotspot"
    password: !secret esp8266-02.wifi.ap.password

captive_portal:

uart:
  tx_pin: GPIO12
  rx_pin: GPIO13
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
