# Transmission
- platform: template
  sensors:
    transmission_switch:
      friendly_name: "Transmission"
      value_template: "{{ states('switch.transmission_switch') }}"
      device_class: power
# Proxmox running
- platform: template
  sensors:
    proxmox_is_running:
      friendly_name: "Proxmox"
      value_template: "{{ states('sensor.proxmox_cpu_usage') | float(0.0) > 0.0 }}"
      device_class: power
# Garbage collection tomorrow
- platform: template
  sensors:
    garbage_collection_tomorrow:
      friendly_name: "Raccolta rifiuti domani"
      value_template: >-
        {{ is_state_attr('sensor.garbage_collection_glass_and_metal', 'daysTo', 1)
        or is_state_attr('sensor.garbage_collection_organic', 'daysTo', 1)
        or is_state_attr('sensor.garbage_collection_paper', 'daysTo', 1)
        or is_state_attr('sensor.garbage_collection_plastic', 'daysTo', 1)
        or is_state_attr('sensor.garbage_collection_trash', 'daysTo', 1) }}
# Late Morning
- platform: tod
  name: Tarda mattinata
  after: "11:00"
  before: "13:00"
# Firestick state (on/off)
- platform: template
  sensors:
    firestick_state:
      value_template: >-
        {% if states('media_player.firestick') == 'off' %} off
        {% else %} on
        {% endif %}
      device_class: power
# Christmas time
- platform: template
  sensors:
    christmas_time:
      value_template: >-
        {% set today = states('sensor.date').split('-') %}
        {% set month = today[1]|int %}
        {% set day = today[2]|int %}
        {{ month == 11 and day >= 22 or month == 12 or month == 1 and day <= 6 }}
