- platform: smartir
  name: Condizionatore Sala
  unique_id: 1d184ea6-2417-11ee-be56-0242ac120002
  device_code: 7000
  controller_data: remote.broadlink_sala
  temperature_sensor: sensor.termometro_sala_temperature
  humidity_sensor: sensor.termometro_sala_humidity
- platform: smartir
  name: Condizionatore Camera
  unique_id: d3a07eba-2416-11ee-be56-0242ac120002
  device_code: 7000
  controller_data: remote.broadlink_camera
  temperature_sensor: sensor.termometro_camera_temperature
  humidity_sensor: sensor.termometro_camera_humidity
- platform: generic_thermostat
  name: Condizionatore Cucina
  unique_id: bdd1928d-a6d4-404f-b9c5-fbd3f74b511e
  min_temp: 15
  max_temp: 30
  precision: 0.5
  target_sensor: sensor.termometro_cucina_temperature
  initial_hvac_mode: "off"
  ac_mode: true
  heater: switch.kitchen_air_conditioner
