# Master Sword
- platform: switch
  name: "Spada Suprema"
  entity_id: switch.esp8266_01_relay
# Piantana Sala
- platform: group
  name: "Piantana Sala"
  entities:
    - light.piantana_sala_luce_grande
    - light.piantana_sala_luce_piccola
# Vetrina ingresso
- platform: switch
  name: "Vetrina Ingresso"
  entity_id: switch.smart_plug_2
# Christmas Tree
- platform: switch
  name: "Albero di Natale"
  entity_id: switch.smart_plug_3
# Group livingroom
- platform: group
  name: "Livingroom"
  entities:
    - light.piantana_sala
# Group entrance
- platform: group
  name: "Entrance"
  entities:
    - light.vetrina_ingresso
# Group bedroom
- platform: group
  name: "Bed"
  entities:
    - light.letto_aronne
    - light.letto_tate
- platform: group
  name: "Bedroom"
  entities:
    - light.bed
    - light.luce_scrivania
