- platform: influxdb
  api_version: 2
  ssl: false
  host: !secret influxdb.ip
  port: !secret influxdb.port
  token: !secret influxdb.token
  organization: !secret influxdb.organization_id
  bucket: !secret influxdb.bucket
  queries_flux:
    # Proxmox CPU load
    - name: proxmox.raw_cpu_usage
      group_function: mean
      range_start: -5m
      query: >
        filter(fn: (r) => r._measurement == "cpustat")
        |> filter(fn: (r) => r._field == "cpu")
        |> map(fn: (r) => ({_time: r._time, _value: r._value * 100.0}))
      unit_of_measurement: "%"
      value_template: "{{ value | float }}"
    # Proxmox memory usage
    - name: proxmox.raw_memory_usage
      group_function: last
      range_start: -5m
      query: >
        filter(fn: (r) => r._measurement == "memory" and r._field == "memused")
        |> map(fn: (r) => ({r with _value: float(v: r._value) / 1073741824.0}))
      unit_of_measurement: "GB"
      value_template: "{{ value | float }}"
    # Proxmox storage usage
    - name: proxmox.raw_storage_usage
      group_function: mean
      range_start: -5m
      query: >
        filter(fn: (r) => r._measurement == "system")
        |> filter(fn: (r) => r._field == "used")
      unit_of_measurement: "GB"
      value_template: "{{ value | float }}"
    # Proxmox storage total
    - name: proxmox.raw_storage_total
      group_function: mean
      range_start: -5m
      query: >
        filter(fn: (r) => r._measurement == "system")
        |> filter(fn: (r) => r._field == "total")
      unit_of_measurement: "GB"
      value_template: "{{ value | float }}"
# Proxmox CPU usage
- platform: template
  sensors:
    proxmox_cpu_usage:
      unit_of_measurement: "%"
      value_template: "{{ '%.2f' | format(states('sensor.proxmox_raw_cpu_usage') | float ) }}"
      friendly_name: "Proxmox CPU Usage"
# Proxmox Memory usage
- platform: template
  sensors:
    proxmox_memory_usage:
      unit_of_measurement: "GB"
      value_template: "{{ '%.2f' | format(states('sensor.proxmox_raw_memory_usage') | float ) }}"
      friendly_name: "Proxmox Memory Usage"
# Proxmox Storage usage
- platform: template
  sensors:
    proxmox_storage_usage:
      unit_of_measurement: "%"
      value_template: "{{ '%.2f' | format((states('sensor.proxmox_raw_storage_usage') | float / states('sensor.proxmox_raw_storage_total') | float) * 100) }}"
      friendly_name: "Proxmox Storage Usage"
# Mean temperature
- platform: template
  sensors:
    home_temperature:
      unit_of_measurement: "°C"
      value_template: "{{ '%.1f' | format(((float(states('sensor.termometro_sala_temperature')) + float(states('sensor.termometro_camera_temperature'))) / 2) | float) }}"
      friendly_name: "Home Temperature"
# Mean humidity
- platform: template
  sensors:
    home_humidity:
      unit_of_measurement: "%"
      value_template: "{{ '%.1f' | format(((float(states('sensor.termometro_sala_humidity')) + float(states('sensor.termometro_camera_humidity'))) / 2) | float) }}"
      friendly_name: "Home Humidity"
      icon_template: mdi:water-percent
