# PC Fisso
- platform: wake_on_lan
  name: Fisso
  mac: !secret switch.fisso.mac
  host: !secret switch.fisso.ip
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: fisso
# Dummy switch
- platform: template
  switches:
    dummy_switch:
      friendly_name: "Dummy Switch"
      turn_on:
      turn_off:
# Work Station
- platform: template
  switches:
    work_station:
      friendly_name: "Work Station"
      turn_on:
        service: script.work_station_on
      turn_off:
        service: script.work_station_off
      value_template: "{{ is_state('light.luce_scrivania', 'on') and is_state('switch.casse_pc', 'on') and is_state('switch.fisso', 'off') }}"
# Gaming Station
- platform: template
  switches:
    gaming_station:
      friendly_name: "Gaming Station"
      turn_on:
        service: script.gaming_station_on
      turn_off:
        service: script.gaming_station_off
      value_template: "{{ is_state('light.luce_scrivania', 'on') and is_state('switch.casse_pc', 'on') and is_state('switch.fisso', 'on') }}"
# Water Heater
- platform: template
  switches:
    water_heater:
      friendly_name: Boiler
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.bot_81bb
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.bot_81bb
# Kitchen air conditioner
- platform: template
  switches:
    kitchen_air_conditioner:
      friendly_name: "Kitchen Air Conditioner"
      turn_on:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot.kitchen_air_conditioner.device_id
          command: "turnOn"
      turn_off:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot.kitchen_air_conditioner.device_id
          command: "turnOff"
# Mosquito Repellent
- platform: template
  switches:
    mosquitto_repellent:
      friendly_name: "Mosquito Repellent"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.smart_plug_1
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.smart_plug_1
