# PC Fisso
- platform: wake_on_lan
  name: Fisso
  mac: !secret switch.fisso.mac
  host: !secret switch.fisso.ip
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: fisso
