binary_sensor:
  - device_class: POWER
    default_entity_id: binary_sensor.transmission_switch
    name: Transmission
    unique_id: d8030c95-12c5-41be-b0d4-b4aff369987b
    state: '{{ states(''switch.transmission_switch'') }}'
