binary_sensor:
  - default_entity_id: binary_sensor.christmas_time
    name: Christmas Time
    unique_id: d4b92220-b197-4131-91f0-c99f90ac13b8
    state: >-
      {% set today = states('sensor.date').split('-') %}
      {% set month = today[1]|int %}
      {% set day = today[2]|int %}
      {{ month == 11 and day >= 22 or month == 12 or month == 1 and day <= 6 }}
