binary_sensor:
  - device_class: POWER
    default_entity_id: binary_sensor.proxmox_is_running
    name: Proxmox
    unique_id: c4fb4667-d076-4541-a219-fd6d482110fe
    state: '{{ states(''sensor.proxmox_cpu_usage'') | float(0.0) > 0.0 }}'
