# ESPHome Particulate Sensor using PMSX003

# - Measures Particulates every 150seconds (2.5 minutes)
# - Sends data back to home assistant
# - Shutdowns PMS Sensors laser/ fan beteween readings so maximise the sensors limited life
# - Flashes onboard LED when a measurement is taken

# Hardware
# PMS5003T
# Pin 1 5v (VCC+)
#    2 GND from ESP32
#    3 SET Not connected, and not required see note below
#    4 RX connected to ESP32 TX
#    5 TX connected to ESP32 RX
#    6,7,8 not connected

# NOTE: FAN spin
#  The fan is spun down by the ESP32's pmsx003 module using a software/UART command rather
#  than using PIN 3
#  This is documented here:
#    (Jan16-May10, 2022) https://github.com/esphome/esphome/pull/3053
#    and more background: https://github.com/esphome/feature-requests/issues/2033 & the links is request


substitutions:
  name: "esp32-01"
  #Time between measurement samples
  measurement_interval: "250s" #250s = 2.5minutes

esphome:
  name: ${name}
  friendly_name: ${name}
  on_boot:
    then:
      - delay: 1s
      - script.execute: boot_flash

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32-01.api.encryption_key

ota:
  - platform: esphome
    password: !secret esp32-01.ota.password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name} Fallback Hotspot
    password: !secret esp32-01.wifi.ap.password

captive_portal:

output:
  - platform: gpio
    pin: GPIO02
    id: onboard_led

uart:
  tx_pin: GPIO017 # Used by ESPHome PMS Platform to turn off fan/laser
  rx_pin: GPIO016
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      # Flash LED when new sample measured
      on_value:
        then:
          - script.execute: flash_sample
    update_interval: ${measurement_interval}

script:
  - id: boot_flash
    mode: single
    then:
      - repeat:
          count: 4
          then:
            - output.turn_on: onboard_led
            - delay: 500ms
            - output.turn_off: onboard_led
            - delay: 500ms

  - id: flash_sample
    mode: single
    then:
      - repeat:
          count: 7
          then:
            - script.execute: flash_double_quick
            - delay: 300ms

  - id: flash_double_quick
    mode: single
    then:
      - output.turn_on: onboard_led
      - delay: 30ms
      - output.turn_off: onboard_led
      - delay: 1ms
      - output.turn_on: onboard_led
      - delay: 30ms
      - output.turn_off: onboard_led

button:
  - platform: restart
    name: Restart
