substitutions:
  name: "esp8266-01"

esphome:
  name: ${name}

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp8266-01.api.encryption_key

ota:
  - platform: esphome
    password: !secret esp8266-01.ota.password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret esp8266-01.wifi.ap.password

captive_portal:

switch:
  - platform: gpio
    pin: GPIO14
    name: ${name}-relay
