esphome:
  name: "master-sword"
  friendly_name: "Master Sword"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qxnithwbnZKvfr29axNOVg3j51zlZB0R0jW7jOlGGCg="

ota:
  - platform: esphome
    password: "fbdc6f4c4599fe98ffc506b39ce48e04"

wifi:
  ssid: !secret wifi.ssid
  password: !secret wifi.password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "master-sword"
    password: "bmChb8dr3hdO"

captive_portal:

switch:
  - platform: gpio
    pin: 14
    id: master_sword
